// Code generated by https://github.com/j178/leetgo.

package main

import (
    "testing"

    . "github.com/j178/leetgo/testutils/go"
)

var testcases = `
input:
[-2,1,-3,4,-1,2,1,-5,4]
output:
6

input:
[1]
output:
1

input:
[5,4,-1,7,8]
output:
23
`

func Test_maxSubArray(t *testing.T) {
    targetCaseNum := 0
    // targetCaseNum := -1
    if err := RunTestsWithString(t, maxSubArray, testcases, targetCaseNum); err != nil {
        t.Fatal(err)
    }
}
