// Code generated by https://github.com/j178/leetgo

package main

import (
    "testing"

    . "github.com/j178/leetgo/testutils/go"
)

var testcases = `
input:
[1,2,3,4]
output:
[24,12,8,6]

input:
[-1,1,0,-3,3]
output:
[0,0,9,0,0]
`

func Test_productExceptSelf(t *testing.T) {
    targetCaseNum := 0
    // targetCaseNum := -1
    if err := RunTestsWithString(t, productExceptSelf, testcases, targetCaseNum); err != nil {
        t.Fatal(err)
    }
}
