// Code generated by https://github.com/j178/leetgo

package main

import (
    "testing"

    . "github.com/j178/leetgo/testutils/go"
)

var testcases = `
input:
[7,1,5,3,6,4]
output:
5

input:
[7,6,4,3,1]
output:
0
`

func Test_maxProfit(t *testing.T) {
    targetCaseNum := 0
    // targetCaseNum := -1
    if err := RunTestsWithString(t, maxProfit, testcases, targetCaseNum); err != nil {
        t.Fatal(err)
    }
}
