// Code generated by https://github.com/j178/leetgo

package main

import (
    "testing"

    . "github.com/j178/leetgo/testutils/go"
)

var testcases = `
input:
"A man, a plan, a canal: Panama"
output:
true

input:
"race a car"
output:
false

input:
" "
output:
true
`

func Test_isPalindrome(t *testing.T) {
    targetCaseNum := 0
    // targetCaseNum := -1
    if err := RunTestsWithString(t, isPalindrome, testcases, targetCaseNum); err != nil {
        t.Fatal(err)
    }
}
