// Code generated by https://github.com/j178/leetgo

package main

import (
    "testing"

    . "github.com/j178/leetgo/testutils/go"
)

var testcases = `
input:
"()"
output:
true

input:
"()[]{}"
output:
true

input:
"(]"
output:
false
`

func Test_isValid(t *testing.T) {
    targetCaseNum := 0
    // targetCaseNum := -1
    if err := RunTestsWithString(t, isValid, testcases, targetCaseNum); err != nil {
        t.Fatal(err)
    }
}
