// Code generated by https://github.com/j178/leetgo

package main

import (
    "testing"

    . "github.com/j178/leetgo/testutils/go"
)

var testcases = `
input:
[1,2,3,1]
output:
true

input:
[1,2,3,4]
output:
false

input:
[1,1,1,3,3,4,3,2,4,2]
output:
true
`

func Test_containsDuplicate(t *testing.T) {
    targetCaseNum := 0
    // targetCaseNum := -1
    if err := RunTestsWithString(t, containsDuplicate, testcases, targetCaseNum); err != nil {
        t.Fatal(err)
    }
}
